NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.tictactoe.sivatech.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.tictactoe.sivatech.com-cert.pem
    OrganizationalUnitIdentifier: peer
