
Profiles:
  TwoOrgOrdererGenesis:
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *TicTacToeOrdererDefaults
      Organizations:
        - *TicTacToeOrdererOrg
      Capabilities:
        <<: *TicTacToeOrdererCapabilities
    Consortiums:
      TicTacToeConsortium:
        Organizations:
          - *Org1
          - *Org2
  TicTacToeChannel:
    Consortium: TicTacToeConsortium
    Application:
      <<: *TicTacToeApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
      Capabilities:
        <<: *TicTacToeApplicationCapabilities

Organizations:
  - &TicTacToeOrdererOrg
      Name: TicTacToeOrdererMSP
      ID: TicTacToeOrdererMSP
      MSPDir: crypto-config/ordererOrganizations/tictactoe.com/msp
  - &Org1
      Name: Org1TicTacToeMSP
      ID: Org1TicTacToeMSP
      MSPDir: crypto-config/peerOrganizations/org1.tictactoe.com/msp
      AnchorPeers:
        - Host: peer0.Org1.tictactoe.com
          Port: 7051
  - &Org2
        Name: Org2TicTacToeMSP
        ID: Org2TicTacToeMSP
        MSPDir: crypto-config/peerOrganizations/org2.tictactoe.com/msp
        AnchorPeers:
          - Host: peer0.Org2.tictactoe.com
            Port: 7051

Orderer: &TicTacToeOrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.tictactoe.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 20
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - 127.0.0.1:9092
  Organizations:


Application: &TicTacToeApplicationDefaults
  Organizations:

Capabilities:
  Global: &ChannelCapabilities
    V1_1: true
  Orderer: &TicTacToeOrdererCapabilities
    V1_1: true
  Application: &TicTacToeApplicationCapabilities
    V1_1: true