
OrdererOrgs:
  - Name: Orderer
    Domain: tictactoe.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.tictactoe.com
    EnableNodeOUs: true
    Template:
      Count: 2

  - Name: Org2
    Domain: org2.tictactoe.com
    EnableNodeOUs: true
    Template:
      Count: 2