
version: '2'

services:
  orderer.tictactoe.com:
    container_name: orderer.tictactoe.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=TicTacToeOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/tictactoe.com/orderers/orderer.tictactoe.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/tictactoe.com/orderers/orderer.tictactoe.com/tls:/var/hyperledger/orderer/tls
      - orderer.tictactoe.com:/opt/gopath/src/chaincode/input
    ports:
      - 7050:7050

  peer0.org1.tictactoe.com:
    container_name: peer0.org1.tictactoe.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.tictactoe.com
      - CORE_PEER_ADDRESS=peer0.org1.tictactoe.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.tictactoe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.tictactoe.com:7051
      - CORE_PEER_LOCALMSPID=Org1TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.tictactoe.com/peers/peer0.org1.tictactoe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.tictactoe.com/peers/peer0.org1.tictactoe.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.tictactoe.com:/opt/gopath/src/chaincode/input
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.tictactoe.com:
    container_name: peer1.org1.tictactoe.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.tictactoe.com
      - CORE_PEER_ADDRESS=peer1.org1.tictactoe.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.tictactoe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.tictactoe.com:7051
      - CORE_PEER_LOCALMSPID=Org1TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.tictactoe.com/peers/peer1.org1.tictactoe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.tictactoe.com/peers/peer1.org1.tictactoe.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org1.tictactoe.com:/opt/gopath/src/chaincode/input
    ports:
      - 8051:7051
      - 8053:7053


  peer0.org2.tictactoe.com:
    container_name: peer0.org2.tictactoe.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.tictactoe.com
      - CORE_PEER_ADDRESS=peer0.org2.tictactoe.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.tictactoe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.tictactoe.com:7051
      - CORE_PEER_LOCALMSPID=Org2TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.tictactoe.com/peers/peer0.org2.tictactoe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.tictactoe.com/peers/peer0.org2.tictactoe.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org2.tictactoe.com:/opt/gopath/src/chaincode/input
    ports:
      - 7055:7051
      - 7057:7053

  peer1.org2.tictactoe.com:
    container_name: peer1.org2.tictactoe.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.tictactoe.com
      - CORE_PEER_ADDRESS=peer1.org2.tictactoe.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.tictactoe.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.tictactoe.com:7051
      - CORE_PEER_LOCALMSPID=Org2TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.tictactoe.com/peers/peer1.org2.tictactoe.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.tictactoe.com/peers/peer1.org2.tictactoe.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org2.tictactoe.com:/opt/gopath/src/chaincode/input
    ports:
      - 8055:7051
      - 8057:7053

      