
version: '2'

volumes:
  orderer.sivatech.com:
  peer0.tictactoe.sivatech.com:
  peer1.tictactoe.sivatech.com:

networks:
  byfn:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sivatech.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.tictactoe.sivatech.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/70698a190a5cfb9d5c0efb502026de92fd6330c2ffc39fba10468c74a66cff95_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.tictactoe.sivatech.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/70698a190a5cfb9d5c0efb502026de92fd6330c2ffc39fba10468c74a66cff95_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/tictactoe.sivatech.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peer_tictactoe
    networks:
      - byfn

  orderer.sivatech.com:
    extends:
      file: docker-compose-base.yaml
      service: orderer.sivatech.com
    container_name: orderer.sivatech.com
    networks:
      - byfn

  peer0.tictactoe.sivatech.com:
    container_name: peer0.tictactoe.sivatech.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.tictactoe.sivatech.com
    networks:
      - byfn

  peer1.tictactoe.sivatech.com:
    container_name: peer1.tictactoe.sivatech.com
    extends:
      file: docker-compose-base.yaml
      service: peer1.tictactoe.sivatech.com
    networks:
      - byfn