
version: '2'

services:
  orderer.sivatech.com:
    container_name: orderer.sivatech.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=SivaTechOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/sivatech.com/orderers/orderer.sivatech.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/sivatech.com/orderers/orderer.sivatech.com/tls:/var/hyperledger/orderer/tls
      - orderer.sivatech.com:/opt/gopath/src/chaincode/input
    ports:
      - 7050:7050

  peer0.tictactoe.sivatech.com:
    container_name: peer0.tictactoe.sivatech.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.tictactoe.sivatech.com
      - CORE_PEER_ADDRESS=peer0.tictactoe.sivatech.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.tictactoe.sivatech.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tictactoe.sivatech.com:7051
      - CORE_PEER_LOCALMSPID=TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/tictactoe.sivatech.com/peers/peer0.tictactoe.sivatech.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/tictactoe.sivatech.com/peers/peer0.tictactoe.sivatech.com/tls:/etc/hyperledger/fabric/tls
      - peer0.tictactoe.sivatech.com:/opt/gopath/src/chaincode/input
    ports:
      - 7051:7051
      - 7053:7053

  peer1.tictactoe.sivatech.com:
    container_name: peer1.tictactoe.sivatech.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.tictactoe.sivatech.com
      - CORE_PEER_ADDRESS=peer1.tictactoe.sivatech.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tictactoe.sivatech.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.tictactoe.sivatech.com:7051
      - CORE_PEER_LOCALMSPID=TicTacToeMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/tictactoe.sivatech.com/peers/peer1.tictactoe.sivatech.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/tictactoe.sivatech.com/peers/peer1.tictactoe.sivatech.com/tls:/etc/hyperledger/fabric/tls
      - peer1.tictactoe.sivatech.com:/opt/gopath/src/chaincode/input
    ports:
      - 8051:7051
      - 8053:7053

      